version: '3.1'

services:

  db:
    build:
      context: ./docker/postgres
    image: postgres:10.5-ja
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      #POSTGRES_PASSWORD: passwd
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d/
      - ./docker/postgres/data:/var/lib/postgresql/data/
      - ./docker/postgres/conf:/etc/postgresql/

